version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: user_service_db,order_service_db
      MYSQL_USER: microservices
      MYSQL_PASSWORD: microservices
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   # UI
      - "14268:14268"   # Collector HTTP
      - "14250:14250"   # Collector gRPC
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "50051:50051"
      - "9091:9091"
    depends_on:
      mysql:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      - CONFIG_FILE=/app/config.yaml

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "50052:50052"
      - "9092:9092"
    depends_on:
      mysql:
        condition: service_healthy
      jaeger:
        condition: service_started
      user-service:
        condition: service_started
    environment:
      - CONFIG_FILE=/app/config.yaml

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - user-service
      - order-service
    environment:
      - CONFIG_FILE=/app/config.yaml

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:
