server:
  address: ":8080"
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]

services:
  user:
    address: "user-service:50051"
  order:
    address: "order-service:50052"

log:
  level: "debug"

jaeger:
  endpoint: "http://jaeger:14268/api/traces"

metrics:
  address: ":9090"
