apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14250
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 14269
          protocol: TCP
        - containerPort: 9411
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
  - port: 5775
    protocol: UDP
    name: agent-zipkin-compact
  - port: 6831
    protocol: UDP
    name: agent-compact
  - port: 6832
    protocol: UDP
    name: agent-binary
  - port: 5778
    protocol: TCP
    name: config-rest
  - port: 16686
    protocol: TCP
    name: query
  - port: 14250
    protocol: TCP
    name: grpc
  - port: 14268
    protocol: TCP
    name: collector
  - port: 14269
    protocol: TCP
    name: admin
  - port: 9411
    protocol: TCP
    name: zipkin
  selector:
    app: jaeger
