apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- user-service.yaml
- order-service.yaml
- mysql.yaml
- jaeger.yaml
- prometheus.yaml

namespace: microservices

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: microservices
