apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052
          name: grpc
        - containerPort: 9102
          name: metrics
        env:
        - name: CONFIG_PATH
          value: "/config"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 50052
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 50052
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: order-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
  - port: 50052
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 9102
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: order-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  config.yaml: |
    server:
      address: ":50052"
    metrics:
      address: ":9102"
    environment: "production"
    jaeger:
      endpoint: "http://jaeger:14268/api/traces"
    database:
      host: "mysql"
      port: 3306
      username: "root"
      password: "password"
      dbname: "orders"
