global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:9100']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9101']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:9102']
